apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: jenkins-template
  title: Jenkins TestJob
  tags:
    - tibco
spec:
  owner: tibco-templates
  type: bwce

  parameters:
    - title: Fill in some steps
      required:
        - name
        - description
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the BWCE Project
          ui:field: EntityNamePicker
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: A description for the BWCE Project

  # This template is meant to be used on top of an existing template.
  # By adding the following and fetching from an absolute URL you can
  # add in the docs template
  steps:
    - id: backstage_request
      name: backstage request
      action: http:backstage:request
      input:
        method: 'POST'
        path: '/proxy/jenkins/TestJob/buildWithParameters'
        params:
          token: 'my-token'
          param1: ${{ parameters.name }}

  output:
    getResponse: '{{ steps.backstage_request.output.body }}'
    getCode: '{{ steps.backstage_request.output.code }}'
    getHeaders: '{{ steps.backstage_request.output.headers }}'
